---
title: "Construction auPRC plots to compare two-species model performance"
author: "Mark Maher Ebeid"
output: html_document
---

# Load libraries, set paths, and define constants
```{r, load libraries}

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggbeeswarm)
library(ggforce)
library(ggpubr)

```
```{r set paths and define constants}

# Declare transciption factors (we want to make quicker prototype sets too)
TFs         <- c("CEBPA", "CTCF", "HNF4A", "RXRA")

# Set the root directory
ROOT        <- getwd()
ROOT_PLOTS  <- file.path(ROOT, "plots", "Figure2")
SAVE        <- FALSE

```
## Load the performance data we saved
- This was generated by the script `_generate_performance_data.ipynb`
```{r load csvs}

performance_metrics     <- read.csv(file.path(ROOT_PLOTS, "performance_data.csv"))

# We divy then up based on the evaluation species
mouse_target_metrics    <- performance_metrics[performance_metrics$Eval == "mm10",]
human_target_metrics    <- performance_metrics[performance_metrics$Eval == "hg38",]

```
# Create performance figures
## Target=human (which means Source=mouse)
```{r}

# Remove the intra-species performance for the domain-adaptive models!
df <- human_target_metrics[human_target_metrics$Model != "Human-trained (+GRL)" & human_target_metrics$Model != "Human-trained (+MORALE)",]
df$Model[df$Model == "Mouse-trained"]           <- "Source"
df$Model[df$Model == "Mouse-trained (+GRL)"]    <- "GRL"
df$Model[df$Model == "Mouse-trained (+MORALE)"] <- "MORALE"
df$Model[df$Model == "Human-trained"]           <- "Target"
df$Model                                        <- factor(df$Model, levels = c("Source", "GRL", "MORALE", "Target"))

```
```{r}

compare_means(auPRC ~ Model, df, method = "t.test", paired = T)

my_comparisons <- list(
    c("Source", "GRL"),
    c("Source", "MORALE"),
    c("Source", "Target"),
    c("GRL", "MORALE"),
    c("GRL", "Target"),
    c("MORALE", "Target")
)

human_target_plot <- ggplot(data = df, aes(x = Model, y = auPRC, color = Model)) +
    geom_beeswarm( # Fake border
        cex = 3,
        priority = "density",
        size = 5.0,
        color = "black",
        fill = NA
    ) +
    geom_beeswarm( # Actual points
        cex = 3,
        priority = "density",
        size = 4.0,
    ) +
    xlab(NULL) +
    labs(
        colour = "Model"
    ) +
    ylab("Area Under PRC") +
    geom_hline(
        data = df |> group_by(TF, Model) |> summarise(mean_auPRC = mean(auPRC)) |> filter(Model == "Source"),
        aes(yintercept = mean_auPRC),
        linetype = 2
    ) +
    facet_wrap(~ TF, scales = "free_y", nrow=1, ncol=4) +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1, size = 14, face = "plain"),
        axis.text.y = element_text(hjust = 1, size = 16, face = "plain"),
        axis.title.y = element_text(size = 18, face = "plain"),
        panel.spacing.x = unit(1, "lines"),
        panel.border = element_rect(colour = "black", fill = NA, size = 1.5),
        strip.text = element_text(face = "bold", size = 12),
        legend.position = "none"
    ) + stat_compare_means(method = "t.test", paired = T, comparisons = my_comparisons)

if (SAVE) {
    ggsave(
        filename = file.path(ROOT_PLOTS, "auPRCs_train-mm10_test-hg38.pdf"),
        plot = human_target_plot,
        device = "pdf",
        dpi = 600
    )
} else {
    human_target_plot
}

```
## Target=mouse (which means source=Human)
```{r}

# Remove the intra-species performance for the domain-adaptive models!
df <- mouse_target_metrics[mouse_target_metrics$Model != "Mouse-trained (+GRL)" & mouse_target_metrics$Model != "Mouse-trained (+MORALE)",]
df$Model[df$Model == "Human-trained"]           <- "Source"
df$Model[df$Model == "Human-trained (+GRL)"]    <- "GRL"
df$Model[df$Model == "Human-trained (+MORALE)"] <- "MORALE"
df$Model[df$Model == "Mouse-trained"]           <- "Target"
df$Model                                        <- factor(df$Model, levels = c("Source", "GRL", "MORALE", "Target"))

```
```{r}

compare_means(auPRC ~ Model, df, method = "t.test", paired = T)

my_comparisons <- list(
    c("Source", "GRL"),
    c("Source", "MORALE"),
    c("Source", "Target"),
    c("GRL", "MORALE"),
    c("GRL", "Target"),
    c("MORALE", "Target")
)

mouse_target_plot <- ggplot(data = df, aes(x = Model, y = auPRC, color = Model)) +
    geom_beeswarm( # Fake border
        cex = 3,
        priority = "density",
        size = 5.0,
        color = "black",
        fill = NA
    ) +
    geom_beeswarm( # Actual points
        cex = 3,
        priority = "density",
        size = 4.0,
    ) +
    xlab(NULL) +
    labs(
        colour = "Model"
        ) +
    ylab("Area Under PRC") +
    geom_hline(
        data = df |> group_by(TF, Model) |> summarise(mean_auPRC = mean(auPRC)) |> filter(Model == "Source"),
        aes(yintercept = mean_auPRC),
        linetype = 2
    ) +
    facet_wrap(~ TF, scales = "free_y", nrow=1, ncol=4) +
    theme(
        axis.text.x = element_text(angle = 45, hjust = 1, size = 14, face = "plain"),
        axis.text.y = element_text(hjust = 1, size = 16, face = "plain"),
        axis.title.y = element_text(size = 18, face = "plain"),
        panel.spacing.x = unit(1, "lines"),
        panel.border = element_rect(colour = "black", fill = NA, size = 1.5),
        strip.text = element_text(face = "bold", size = 12),
        legend.position = "none"
    ) + stat_compare_means(method = "t.test", paired = T, comparisons = my_comparisons)

if (SAVE) {
    ggsave(
        filename = file.path(ROOT_PLOTS, "auPRCs_train-hg38_test-mm10.pdf"),
        plot = mouse_target_plot,
        device = "pdf",
        dpi = 600
    )
} else {
    mouse_target_plot
}

```